FROM jwilder/nginx-proxy:alpine
#FROM i3c/i3cp/nginx-proxy
#https://github.com/jwilder/nginx-proxy

RUN apk --no-cache add dnsmasq
EXPOSE 53 53/udp

#RUN cp -rp /app /app.backup

COPY run-i3cp.sh /
RUN chmod a+x /run-i3cp.sh \
	&& ln -sf /run-i3cp.sh /r
ENTRYPOINT ["/r"]
CMD ["startup"]