FROM i3c/mqtt-base

RUN apk add bash

COPY run-mqtt.sh /
RUN  chmod a+x /run-mqtt.sh && ln -sf /run-mqtt.sh /r

RUN cp -rp /mosquitto/config /mosquitto/config.backup



ENTRYPOINT ["/r"]
CMD [ "startup"]