FROM alpine:latest
RUN apk --no-cache --update upgrade && apk --no-cache add ca-certificates

RUN apk update \
	&& apk upgrade \
	&& apk add bash git yarn docker

#docker-compose
#RUN apk add py-pip \
#	&& pip install docker-compose

VOLUME /i3c

WORKDIR /

COPY waitReady.sh /
COPY run.sh /run-i3c.sh
RUN chmod a+x /*.sh \
	&& ln -s /run-i3c.sh /r

ENTRYPOINT ["/r"]
CMD ["startup"]

