#docker run -it -p 1880:1880 --name mynodered nodered/node-red-docker
#FROM nodered/node-red-docker
FROM nodered/node-red-docker:slim

USER root
RUN apk --no-cache --update upgrade && apk --no-cache add ca-certificates
RUN apk update \
	&& apk upgrade \
	&& apk add bash git docker  zip
	
#RUN apk add	python python-dev make g++	

#VOLUME /i3c
RUN adduser node-red docker && adduser node-red users

USER node-red

RUN cd /usr/src/node-red && npm install passport-github \
      && npm install string 
#      && npm install exec-php
