FROM node:alpine
#USER root
#RUN  apt-get update \
#	&& apt-get install sudo \
#RUN npm install -g --no-bin-links loopback-cli 

RUN apk update \
	&& apk add bash git
	
RUN apk add	python python-dev  
		