#https://strongloop.com/strongblog/soap-into-rest-apis-with-loopback-node-js/
#https://strongloop.com/strongblog/generating-swagger-openapi-specification-from-your-loopback-application/
#https://github.com/strongloop-community/loopback-example-connector
version: '3'
services:
  trigger:
    environment:
      PWD_SESSION_ID: ${SESSION_ID}
      PWD_HOST_IP: ${PWD_HOST_IP}
      PWD_HOST_FQDN: ${PWD_HOST_FQDN}
    image: franela/dind
    command: sh -c "curl -sSL https://raw.githubusercontent.com/virtimus/i3c/master/bs-loopback-example.sh | bash >> /log/bs-loopback-example.log 2>&1 && tail -f /dev/null"
    volumes: [ '/var/log:/log' ]
