FROM i3c/base/ubuntu18

# Build-time metadata as defined at http://label-schema.org
ARG PROJECT_NAME
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="$PROJECT_NAME" \
      org.label-schema.description="A Ubuntu image that is updated daily to provide the latest packages" \
      org.label-schema.url="https://www.ubuntu.com/" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/vcatechnology/docker-ubuntu" \
      org.label-schema.vendor="VCA Technology" \
      org.label-schema.version=$VERSION \
      org.label-schema.license=MIT \
      org.label-schema.schema-version="1.0"

# Make sure APT operations are non-interactive
ENV DEBIAN_FRONTEND noninteractive

# Create install script
RUN touch                                                                 /usr/local/bin/vca-install-package \
	&& chmod +x                                                              /usr/local/bin/vca-install-package \
	&& echo '#! /bin/sh'                                                  >> /usr/local/bin/vca-install-package \
	&& echo 'set -e'                                                      >> /usr/local/bin/vca-install-package \
	&& echo 'apt-get -q update'                                           >> /usr/local/bin/vca-install-package \
	&& echo 'apt-get -qy -o Dpkg::Options::="--force-confnew" install $@' >> /usr/local/bin/vca-install-package \
	&& echo 'apt-get -qy clean'                                           >> /usr/local/bin/vca-install-package

# Create uninstall script
RUN touch                                   /usr/local/bin/vca-uninstall-package \
	&& chmod +x                                /usr/local/bin/vca-uninstall-package \
	&& echo '#! /bin/sh'                    >> /usr/local/bin/vca-uninstall-package \
	&& echo 'set -e'                        >> /usr/local/bin/vca-uninstall-package \
	&& echo 'apt-get -qy remove --purge $@' >> /usr/local/bin/vca-uninstall-package \
	&& echo 'apt-get -qy autoremove'        >> /usr/local/bin/vca-uninstall-package \
 	&& echo 'apt-get -qy clean'             >> /usr/local/bin/vca-uninstall-package

# Generate locales
RUN vca-install-package apt-utils \
	&& vca-install-package locales language-pack-en \
	&& echo "LANG=en_US.UTF-8" > /etc/default/locale \
	&& update-locale LANG=en_US.UTF-8
	
ENV LANG=en_US.UTF-8

# Set up the timezone
RUN vca-install-package tzdata \
	&& echo "Europe/Warsaw" > /etc/timezone \
	&& dpkg-reconfigure tzdata

# Update all packages
RUN apt-get -q update \
	&& apt-get -qy -o Dpkg::Options::="--force-confnew" dist-upgrade \
	&& apt-get -qy autoremove \
	&& apt-get -q clean
	
#install some packs	
RUN apt-get install -y gnupg2	


	
#	&& echo "deb http://extra.linuxmint.com tara main" >> ${REPO_LIST} \	
# Set up the Linux Mint repositories

RUN REPO_LIST=/etc/apt/sources.list.d/mint.list \
	&& echo "deb http://packages.linuxmint.com/ tara main upstream import backport " > ${REPO_LIST} \
#	&& echo "deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse" >> ${REPO_LIST} \
#	&& echo "deb http://archive.ubuntu.com/ubuntu/ bionic universe multiverse" >> ${REPO_LIST} \
#	&& echo "deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse" >> ${REPO_LIST} \
#	&& echo "deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse" >> ${REPO_LIST} \
#	&& echo "deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse" >> ${REPO_LIST} \
#	&& echo "deb http://archive.canonical.com/ubuntu/ bionic partner" >> ${REPO_LIST} \
#	&& echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic universe multiverse" >> ${REPO_LIST} \
#	&& echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic-updates universe multiverse" >> ${REPO_LIST} \
#	&& echo "deb-src http://security.ubuntu.com/ubuntu/ bionic-security universe multiverse" >> ${REPO_LIST} \
#RUN REPO_LIST=/etc/apt/sources.list \
#	&& cp ${REPO_LIST} ${REPO_LIST}.bak \
#	&& echo "#deb cdrom:[Linux Mint 19 _Tara_ - Release amd64 20180717]/ bionic contrib main non-free" > ${REPO_LIST} \
#	&& echo "deb http://packages.linuxmint.com tara main upstream import backport #id:linuxmint_main" >> ${REPO_LIST} \
#	&& cat ${REPO_LIST}.bak >> ${REPO_LIST} \
	&& LINUX_MINT_KEY=$(apt update 2>&1 | grep -o '[0-9A-Z]\{16\}$' | xargs) \
	&& apt-key adv --recv-keys --keyserver keyserver.ubuntu.com ${LINUX_MINT_KEY} \
	&& vca-install-package --allow-unauthenticated linuxmint-keyring \
	&& unset LINUX_MINT_KEY REPO_LIST

# Install the necessary packages to convert to Linux Mint
RUN vca-install-package base-files

# Update all packages
RUN apt-get -q update \
	&& echo console-setup console-setup/charmap select UTF-8 | debconf-set-selections \
	&& apt-get -fqy -o Dpkg::Options::="--force-confnew" -o APT::Immediate-Configure=false dist-upgrade \
	&& apt-get -qy autoremove \
	&& apt-get -q clean	
