FROM i3c/base/ubuntu18/mint as builder

# Install packages

ENV DEBIAN_FRONTEND noninteractive
RUN sed -i "s/# deb-src/deb-src/g" /etc/apt/sources.list
RUN apt-get -y update
RUN apt-get -yy upgrade
ENV BUILD_DEPS="git autoconf pkg-config libssl-dev libpam0g-dev \
    libx11-dev libxfixes-dev libxrandr-dev nasm xsltproc flex \
    bison libxml2-dev dpkg-dev libcap-dev"
RUN apt-get -yy install  sudo apt-utils software-properties-common $BUILD_DEPS


# Build xrdp

WORKDIR /tmp
RUN apt-get source pulseaudio
RUN apt-get build-dep -yy pulseaudio
WORKDIR /tmp/pulseaudio-11.1
RUN dpkg-buildpackage -rfakeroot -uc -b
WORKDIR /tmp
RUN git clone --branch v0.9.7 --recursive https://github.com/neutrinolabs/xrdp.git
WORKDIR /tmp/xrdp
RUN ./bootstrap
RUN ./configure
RUN make
RUN make install
WORKDIR /tmp/xrdp/sesman/chansrv/pulse
RUN sed -i "s/\/tmp\/pulseaudio\-10\.0/\/tmp\/pulseaudio\-11\.1/g" Makefile
RUN make
RUN mkdir -p /tmp/so
RUN cp *.so /tmp/so
##################################################################################
##################################################################################
FROM i3c/base/ubuntu18/mint 

ENV DEBIAN_FRONTEND noninteractive

#  xfce4 xfce4-terminal xfce4-screenshooter xfce4-taskmanager \
#  xfce4-clipman-plugin xfce4-cpugraph-plugin xfce4-netload-plugin \
#  xfce4-xkb-plugin 
RUN apt-get -y update \
	&& apt install -yy vim wget ca-certificates xorgxrdp pulseaudio xrdp \
	xauth supervisor uuid-runtime locales \
	firefox pepperflashplugin-nonfree openssh-server sudo \
	&& mkdir -p /var/lib/xrdp-pulseaudio-installer
	
COPY --from=builder /tmp/so/module-xrdp-source.so /var/lib/xrdp-pulseaudio-installer
COPY --from=builder /tmp/so/module-xrdp-sink.so /var/lib/xrdp-pulseaudio-installer


#cinamon
#RUN add-apt-repository universe \
#cinnamon-desktop-environment
RUN	apt-get install -y cinnamon-desktop-environment mint-meta-core mint-meta-cinnamon lightdm

ADD bin /usr/bin
ADD etc /etc
#ADD pulse /usr/lib/pulse-10.0/modules/
#RUN locale-gen en_US.UTF-8
#RUN echo "xfce4-session" > /etc/skel/.Xclients
# Configure
RUN mkdir /var/run/dbus \
	&& cp /etc/X11/xrdp/xorg.conf /etc/X11 \
	&& sed -i "s/console/anybody/g" /etc/X11/Xwrapper.config \
	&& sed -i "s/xrdp\/xorg/xorg/g" /etc/xrdp/sesman.ini \
	&& cp -r /etc/ssh /ssh_orig \
	&& rm -rf /etc/ssh/* \
	&& rm -rf /etc/xrdp/rsakeys.ini /etc/xrdp/*.pem

#mint-info-cinnamon
#	Errors were encountered while processing:
#	 /tmp/apt-dpkg-install-cmvIGq/09-mint-info-cinnamon_2018.02.07_all.deb - 

# Add sample user & some additions
RUN addgroup ubuntu \
	&& useradd -m -s /bin/bash -g ubuntu ubuntu \
	&& echo "ubuntu:ubuntu" | /usr/sbin/chpasswd \
	&& echo "ubuntu    ALL=(ALL) ALL" >> /etc/sudoers \
	&& apt-get install -y mlocate \
	&& apt-get install -y cinnamon-control-center-dbg cinnamon-dbg  mintlocale mintmenu mintreport \
	&& apt-get remove -y mint-info-xfce \
	&& apt-get install -y mint-info-cinnamon \
	&& apt-get purge nvidia \
	&& mkdir -p /run/dbus \
	&& chown messagebus:messagebus /run/dbus \
	&& dbus-uuidgen --ensure 
	
	

#sys config
#ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket 
# 
# chown messagebus:messagebus /run/dbus
# dbus-uuidgen --ensure
# Docker config
VOLUME ["/etc/ssh","/home"]
EXPOSE 3389 22 9001
COPY run-xrdp-mint.sh / 
COPY run-startup.sh /
RUN chmod a+x /run-startup.sh && chmod a+x /run-xrdp-mint.sh && ln -sf /run-xrdp-mint.sh /r

#ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
#CMD ["supervisord"]
